### ISSUE TITLE
Use dynamic github contributions chart

### ISSUE THREAD

**Issue by kaustubhhiware** [Demfier/demfier.github.io#16]
Instead of a static screenshot,can use something like [ghchart](https://github.com/2016rshah/githubchart-api).

![image](https://user-images.githubusercontent.com/11318551/34163002-8c654c20-e4fb-11e7-9789-354949c83017.png)

Allows for customising colours.

**Comment by Demfier** [comment]
It is not a static screenshot :smile: 
I have used [github-calender.js](https://github.com/IonicaBizau/github-calendar)

It doens't allow customized colors though, would be interesting to combine the goods of both of them.

**Comment by kaustubhhiware** [comment]
Did not know this. Will also use this :open_mouth:
